# -*- coding: utf-8 -*-
"""factorial.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LVlavVgx_vqtTGKXeow6CY2M-s39Xia1
"""

# Python translation of the C factorial code
try:
    num = int(input("Enter a number: "))
    if num < 0:
        print("Factorial is not defined for negative numbers.")
    elif num == 0:
        print("The factorial of 0 is 1")
    else:
        factorial_result = 1
        for i in range(1, num + 1):
            factorial_result = factorial_result * i
        print(f"Factorial of {num} is {factorial_result}")
except ValueError:
    print("Invalid input. Please enter an integer.")