# -*- coding: utf-8 -*-
"""session4-25bcon0937.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MMe3oOPdD4VHKnYsyxlIWStS0METXXV1

factorial colab
"""

# Python translation of the C Fibonacci series code
try:
    n = int(input("Enter the number of terms: "))

    first = 0
    second = 1

    print("Fibonacci Series:", end=" ")

    if n <= 0:
        print("Please enter a positive integer.")
    elif n == 1:
        print(first)
    else:
        for i in range(n):
            print(first, end=" ")
            next_term = first + second
            first = second
            second = next_term
        print()
except ValueError:
    print("Invalid input. Please enter an integer.")