# -*- coding: utf-8 -*-
"""session4-25bcon0937.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MMe3oOPdD4VHKnYsyxlIWStS0METXXV1

factorial colab
"""

#include <stdio.h>

int main() {
    int n;
    long long factorial = 1;

    printf("Enter a number: ");
    scanf("%d", &n);

    for (int i = 1; i <= n; i++) {
        factorial = factorial * i;
    }

    printf("Factorial of %d is %lld\n", n, factorial);

    return 0;
}

# Python translation of the C factorial code
try:
    num = int(input("Enter a number: "))
    if num < 0:
        print("Factorial is not defined for negative numbers.")
    elif num == 0:
        print("The factorial of 0 is 1")
    else:
        factorial_result = 1
        for i in range(1, num + 1):
            factorial_result = factorial_result * i
        print(f"Factorial of {num} is {factorial_result}")
except ValueError:
    print("Invalid input. Please enter an integer.")

# Python translation of the C Fibonacci series code
try:
    n = int(input("Enter the number of terms: "))

    first = 0
    second = 1

    print("Fibonacci Series:", end=" ")

    if n <= 0:
        print("Please enter a positive integer.")
    elif n == 1:
        print(first)
    else:
        for i in range(n):
            print(first, end=" ")
            next_term = first + second
            first = second
            second = next_term
        print()
except ValueError:
    print("Invalid input. Please enter an integer.")